project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: false
  resources:
    - "data"

book:
  title: "Learning Econometrics with Python"
  author: "Lucas A. Meyer"
  date: "6/14/2022"
  chapters:
    - index.qmd
    - 01-linear-regression.qmd
    - data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



